### singup 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "test"
}

### signin 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

### signout 
POST http://localhost:3000/auth/signout


### currentuser 
GET http://localhost:3000/auth/currentuser


### Find a User with given ID
GET http://localhost:3000/auth/4

### Find All Users with given email
GET http://localhost:3000/auth?email=test@test.com

### Delete a User with given ID
DELETE http://localhost:3000/auth/2

### Update a User with given ID
PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "test1"
}